name: studyspritz
description: A new Flutter project

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # FILE PICKER
  file_picker: ^8.0.0

  # PDF PARSING (cross-platform)
  syncfusion_flutter_pdf: ^28.1.0

  # DOCX (zip parsing)
  archive: ^3.4.10

  # LOCAL STORAGE
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  go_router: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6